version: "3.8"

services:
  reverse-proxy:
    image: nginx:1.31.0
    ports:
      - target: <port>
        published: <port>
        protocol: tcp
        mode: host
    secrets:
      - source: internal_ca_crt
        target: /etc/nginx/ssl/internal-ca.crt
      - source: htpasswd_admin
        target: /etc/nginx/htpasswd-admin
    volumes:
      - /etc/letsencrypt/live/<hostname>/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/<hostname>/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./config/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test:
        ["CMD-SHELL", "curl -fsSk https://localhost:<port>/ | grep -q '<html'"]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s
    networks:
      - proxy

  frontend:
    image: ghcr.io/frhorschig/kant-search-frontend:<version>
    secrets:
      - source: frontend_crt
        target: /etc/nginx/ssl/frontend.crt
      - source: frontend_key
        target: /etc/nginx/ssl/frontend.key
    volumes:
      - ./config/frontend/config.json:/usr/share/nginx/html/assets/config.json:ro
      - ./config/frontend/i18n:/usr/share/nginx/html/assets/i18n:ro
      - ./config/frontend/startpage:/usr/share/nginx/html/assets/startpage:ro
    environment:
      - BASE_PATH=<base-path>
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --insecure https://localhost/index.html | grep -q '<title'",
        ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s
    networks:
      - proxy

  backend:
    image: ghcr.io/frhorschig/kant-search-backend:<version>
    secrets:
      - source: internal_ca_crt
        target: /app/certs/internal-ca.crt
      - source: backend_crt
        target: /app/certs/backend.crt
      - source: backend_key
        target: /app/certs/backend.key
      - source: ksdb_password
        target: ksdb_password
    volumes:
      - ./config/backend:/app/config:ro
      - ./log/backend:/var/log/kant-search-backend
    environment:
      - KSDB_URL=https://elasticsearch
      - KSDB_PORT=9200
      - KSDB_USERNAME=elastic
      - KSDB_PASSWORD=/run/secrets/ksdb_password
      - KSDB_CERT=/app/certs/internal-ca.crt
      - KSGO_CONFIG_PATH=/app/config
      - KSGO_CERT=/app/certs/backend.crt
      - KSGO_KEY=/app/certs/backend.key
      - KSGO_ALLOW_ORIGINS=https://<hostname>
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cert /app/certs/backend.crt --key /app/certs/backend.key --cacert /app/certs/internal-ca.crt https://localhost:5000/api/v1/health | grep -q 'UP'",
        ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s
    networks:
      - proxy
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.4
    secrets:
      - source: internal_ca_crt
        target: /usr/share/elasticsearch/config/certs/internal-ca.crt
      - source: elasticsearch_crt
        target: /usr/share/elasticsearch/config/certs/elasticsearch.crt
      - source: elasticsearch_key
        target: /usr/share/elasticsearch/config/certs/elasticsearch.key
      - source: ksdb_password
        target: /run/secrets/ksdb_password
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=/run/secrets/ksdb_password
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=certs/internal-ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/internal-ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert /usr/share/elasticsearch/config/certs/internal-ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - backend

  grafana:
    image: grafana/grafana:12.1.0
    secrets:
      - source: internal_ca_crt
        target: /etc/grafana/ssl/internal-ca.crt
      - source: grafana_crt
        target: /etc/grafana/ssl/grafana.crt
      - source: grafana_key
        target: /etc/grafana/ssl/grafana.key
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    deploy:
      replicas: 1
    networks:
      - proxy

  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    deploy:
      replicas: 1
    networks:
      - proxy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      replicas: 1
    networks:
      - proxy

secrets:
  internal_ca_crt:
    external: true
  frontend_crt:
    external: true
  frontend_key:
    external: true
  backend_crt:
    external: true
  backend_key:
    external: true
  elasticsearch_crt:
    external: true
  elasticsearch_key:
    external: true
  grafana_crt:
    external: true
  grafana_key:
    external: true
  htpasswd_admin:
    external: true
  ksdb_password:
    external: true

volumes:
  elastic-data:
  grafana-data:
  prometheus-data:

networks:
  proxy:
    driver: overlay
  backend:
    driver: overlay
