version: "3.8"

services:
  reverse-proxy:
    image: nginx:1.29.0
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - /etc/letsencrypt/live/<hostname>/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/<hostname>/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./auth/internal-ca.crt:/etc/nginx/ssl/internal-ca.crt:ro
      - ./auth/htpasswd-admin:/etc/nginx/htpasswd-admin:ro
      - ./config/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test:
        ["CMD-SHELL", "curl -s --insecure https://localhost/ | grep -q '<html'"]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s
    networks:
      - proxy

  frontend:
    image: ghcr.io/frhorschig/kant-search-frontend:0.9.0
    volumes:
      - ./auth/frontend.crt:/etc/nginx/ssl/frontend.crt:ro
      - ./auth/frontend.key:/etc/nginx/ssl/frontend.key:ro
      - ./config/frontend/config.json:/usr/share/nginx/html/assets/config.json:ro
      - ./config/frontend/i18n:/usr/share/nginx/html/assets/i18n:ro
      - ./config/frontend/startpage:/usr/share/nginx/html/assets/startpage:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --insecure https://localhost/index.html | grep -q '<title'",
        ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s
    networks:
      - proxy

  backend:
    image: ghcr.io/frhorschig/kant-search-backend:0.9.0
    volumes:
      - ./config/backend:/app/config:ro
      - ./auth:/app/certs:ro
      - ./logs/backend:/var/logs/kant-search-backend
    secrets:
      - ksdb_password
    environment:
      - KSDB_URL=https://elasticsearch
      - KSDB_PORT=9200
      - KSDB_USERNAME=elastic
      - KSDB_PASSWORD=/run/secrets/ksdb_password
      - KSDB_CERT=/app/certs/internal-ca.crt
      - KSGO_CONFIG_PATH=/app/config
      - KSGO_CERT=/app/certs/backend.crt
      - KSGO_KEY=/app/certs/backend.key
      - KSGO_ALLOW_ORIGINS=https://<hostname>
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cert /app/certs/backend.crt --key /app/certs/backend.key --cacert /app/certs/internal-ca.crt https://localhost:5000/api/v1/health | grep -q 'UP'",
        ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s
    networks:
      - proxy
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.4
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
      - ./auth:/usr/share/elasticsearch/config/certs:ro
    secrets:
      - ksdb_password
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=/run/secrets/ksdb_password
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=certs/internal-ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/internal-ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/internal-ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - backend

  grafana:
    image: grafana/grafana:12.1.0
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./auth/grafana.crt:/etc/grafana/ssl/grafana.crt:ro
      - ./auth/grafana.key:/etc/grafana/ssl/grafana.key:ro
      - ./auth/internal-ca.crt:/etc/grafana/ssl/internal-ca.crt:ro
    deploy:
      replicas: 1
    networks:
      - proxy

  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    deploy:
      replicas: 1
    networks:
      - proxy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      replicas: 1
    networks:
      - proxy

secrets:
  ksdb_password:
    external: true

volumes:
  elastic-data:
  grafana-data:
  prometheus-data:

networks:
  proxy:
    driver: overlay
  backend:
    driver: overlay
